### ISSUE TITLE
actions.set wegmachen

### ISSUE THREAD

**Issue by L3P3** [LFF5644/site-Game2D#1]
Schwer zu sagen, aber `.set('key', ...)` führt in die falsche Richtung. :wink:

**Comment by LFF5644** [comment]
es nervt aber immer "set<NAME>"  deswegen "set(<NAME>)" dann muss ich nicht für alles eine function machen

**Comment by L3P3** [comment]
Dann kannst du auch `.patch({...})` nehmen, so kannst du mehrere in einem Render-Durchgang ändern!
